from django.db import models

# Create your models here.
class Students(models.Model):
    StudentId=models.AutoField(primary_key=True)
    FirstName=models.CharField(max_length=100)
    LastName=models.CharField(max_length=100)
    DateofBirth=models.CharField(max_length=100)
    Email=models.CharField(max_length=100)
    Phoneno=models.CharField(max_length=100)
    Gender=models.CharField(max_length=100)
    City=models.CharField(max_length=100)
    State=models.CharField(max_length=100)
    Zip=models.CharField(max_length=100)
    PermanentAddress=models.CharField(max_length=100)
    CorrespondenceAddress=models.CharField(max_length=100)
    Percentage10=models.CharField(max_length=100)
    Percentage12=models.CharField(max_length=100)
    YearofPassing10=models.CharField(max_length=100)
    YearofPassing12=models.CharField(max_length=100)
    College=models.CharField(max_length=100)
    Course=models.CharField(max_length=100)
    Branch=models.CharField(max_length=100)
    Year=models.CharField(max_length=100)
    Certifications=models.CharField(max_length=100)
    InternshiCompany=models.CharField(max_length=100)
    Duration=models.CharField(max_length=100)
    Domain=models.CharField(max_length=100)
    workdescription=models.CharField(max_length=100)
    Projectsundertaken=models.CharField(max_length=100)
    Skills=models.CharField(max_length=100)
    Workexperience=models.CharField(max_length=100)
    Whatareyouplanningaftergraduation=models.CharField(max_length=100)
    Areaofinterest=models.CharField(max_length=100)